### ISSUE TITLE
LIKE 喜欢主题

### ISSUE THREAD

**Issue by baidut** [baidut/markit#25]
添加like表 （即讨论时说的star）
用户喜欢主题是多对多的关系，一个用户可以喜欢多个主题，一个主题可以被多个用户喜欢

在controller/user.php 中添加函数 like_theme （对应的网址是 user/like_theme）
输入为theme_id
处理为在数据库中添加表项 表like， 表theme的like_num（喜欢人数）加一
输出为页面 redirect('explore/themes', 'refresh');

**Comment by wanggangalanhe** [comment]
真的很棒，加油伙伴们
